### ISSUE TITLE
ChatClient::editMessage does not recognise back off delays when called.

### ISSUE THREAD

**Issue by EleventyJeeves** [Room-11/Jeeves#166]
Source - http://chat.stackoverflow.com/transcript/message/35721225#35721225

**Comment by Nessworthy** [comment]
Trigger: Calling !!imdb and receiving a fast API response.
Dump:
```
[2017-02-17 21:38:53] Processing room event #72344290 for built in event handlers
[2017-02-17 21:38:53] Event #72344290 processed for built in event handlers
[2017-02-17 21:38:53] Event #72344290 is not a command, it's a Room11\Jeeves\Chat\Message\Message
[2017-02-17 21:38:53] Processing room event #72344290 for plugins
[2017-02-17 21:38:53] Event #72344290 processed for plugins
[2017-02-17 21:38:54] Starting action executor loop for chat.stackoverflow.com#100286
[2017-02-17 21:38:54] Post attempt 1
[2017-02-17 21:38:54] Got response from server: You can perform this action again in 1 second.
[2017-02-17 21:38:54] Got a 409 response to an Action request that could not be decoded as a back-off delay
string(46) "You can perform this action again in 1 second."
[2017-02-17 21:38:54] Action executor loop terminating for chat.stackoverflow.com#100286
[2017-02-17 21:38:54] Something went wrong while processing event #72344289: InvalidArgumentException in S:\projects\jeeves\src\Chat\Client\ActionExecutor.php:107
Stack trace:
#0 S:\projects\jeeves\src\Chat\Client\ActionExecutor.php(56): Room11\Jeeves\Chat\Client\ActionExecutor->getBackOffDelay('You can perform...')
#1 S:\projects\jeeves\src\Chat\Client\ActionExecutor.php(122): Room11\Jeeves\Chat\Client\ActionExecutor->executeAction(Object(Room11\Jeeves\Chat\Client\Actions\EditMessageAction))
#2 [internal function]: Room11\Jeeves\Chat\Client\ActionExecutor->executeActionsFromQueue('chat.stackoverf...')
#3 S:\projects\jeeves\vendor\amphp\amp\lib\functions.php(876): Generator->send(Object(Amp\Artax\Response))
#4 S:\projects\jeeves\vendor\amphp\amp\lib\Placeholder.php(91): Amp\__coroutineSend(NULL, Object(Amp\Artax\Response), Object(Amp\CoroutineState))
#5 S:\projects\jeeves\vendor\amphp\amp\lib\PrivatePromisor.php(20): Amp\PrivatePlaceholder->resolve(NULL, Object(Amp\Artax\Response))
#6 S:\projects\jeeves\vendor\amphp\amp\lib\PrivatePromisor.php(57): Amp\PrivatePlaceholder->Amp\{closure}(NULL, Object(Amp\Artax\Response))
#7 S:\projects\jeeves\vendor\amphp\artax\lib\Client.php(572): Amp\Deferred->succeed(Object(Amp\Artax\Response))
#8 S:\projects\jeeves\vendor\amphp\artax\lib\Client.php(485): Amp\Artax\Client->assignParsedResponse(Object(Amp\Artax\RequestCycle), Array)
#9 S:\projects\jeeves\vendor\amphp\artax\lib\Client.php(472): Amp\Artax\Client->parseSocketData(Object(Amp\Artax\RequestCycle))
#10 S:\projects\jeeves\vendor\amphp\artax\lib\Client.php(455): Amp\Artax\Client->consumeSocketData(Object(Amp\Artax\RequestCycle), 'HTTP/1.1 409 Co...')
#11 S:\projects\jeeves\vendor\amphp\artax\lib\Client.php(435): Amp\Artax\Client->onReadableSocket(Object(Amp\Artax\RequestCycle))
#12 S:\projects\jeeves\vendor\amphp\amp\lib\NativeReactor.php(265): Amp\Artax\Client->Amp\Artax\{closure}('000000001ec7a09...', Resource id #274, NULL)
#13 S:\projects\jeeves\vendor\amphp\amp\lib\NativeReactor.php(249): Amp\NativeReactor->doIoCallback('000000001ec7a09...', Object(stdClass), Resource id #274)
#14 S:\projects\jeeves\vendor\amphp\amp\lib\NativeReactor.php(214): Amp\NativeReactor->selectActionableStreams(0.0518)
#15 S:\projects\jeeves\vendor\amphp\amp\lib\NativeReactor.php(71): Amp\NativeReactor->doTick(false)
#16 S:\projects\jeeves\vendor\amphp\amp\lib\functions.php(46): Amp\NativeReactor->run(NULL)
#17 S:\projects\jeeves\cli\run.php(246): Amp\run()
#18 {main}
```
